name: simulation

services:
  ros:
    build:
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    # xacro cliを使う際は以下を実行
    # source /opt/ros/jazzy/setup.bash
    volumes:
      - ./data:/app
