[tool.poetry]
name = "simulation"
version = "0.1.0"
description = ""
authors = ["nszknao"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gymnasium = {extras = ["classic-control"], version = "^0.29.1"}
mujoco = "3.1.6"
torch = "2.3.1"
numpy = "1.26.4"
polars = "1.6.0"
hvplot = "0.10.0"
pyarrow = "17.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
