[tool.poetry]
name = "simulation"
version = "0.1.0"
description = ""
authors = ["nszknao"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gymnasium = {extras = ["classic-control"], version = "^0.29.1"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
